# Generated by Django 4.2 on 2025-01-21 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CedioGallary',
            new_name='VedioGallary',
        ),
    ]
