# Generated by Django 4.2 on 2025-01-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_app', '0003_contact_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mobile',
            field=models.CharField(max_length=12),
        ),
    ]
