# Generated by Django 4.2 on 2025-01-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_app', '0004_alter_contact_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('mobile', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=20)),
                ('feedback', models.CharField(max_length=500)),
                ('interior', models.IntegerField(null=True)),
                ('exterior', models.IntegerField(null=True)),
                ('overall', models.IntegerField(null=True)),
                ('suggest', models.CharField(max_length=5)),
            ],
        ),
    ]
